public enum Cards
{
    AUTO_BLANCO,
    AUTO_BLANCO_CHICO,
    AUTO_BLANCO_DOBLE,
    AUTO_BLANCO_DOBLE_CHICO,

    AUTO_ROJO,
    AUTO_ROJO_CHICO,
    AUTO_ROJO_DOBLE,
    AUTO_ROJO_DOBLE_CHICO,

    AUTO_AZUL,
    AUTO_AZUL_CHICO,
    AUTO_AZUL_DOBLE,
    AUTO_AZUL_DOBLE_CHICO,

    AUTO_AMARILLO,
    AUTO_AMARILLO_CHICO,
    AUTO_AMARILLO_DOBLE,
    AUTO_AMARILLO_DOBLE_CHICO,

    AUTO_NARANJA,
    AUTO_NARANJA_CHICO,
    AUTO_NARANJA_DOBLE,
    AUTO_NARANJA_DOBLE_CHICO,


    FLOR_BLANCA,
    FLOR_BLANCA_CHICA,
    FLOR_BLANCA_DOBLE,
    FLOR_BLANCA_DOBLE_CHICA,

    FLOR_ROJA,
    FLOR_ROJA_CHICA,
    FLOR_ROJA_DOBLE,
    FLOR_ROJA_DOBLE_CHICA,

    FLOR_AZUL,
    FLOR_AZUL_CHICA,
    FLOR_AZUL_DOBLE,
    FLOR_AZUL_DOBLE_CHICA,

    FLOR_AMARILLA,
    FLOR_AMARILLA_CHICA,
    FLOR_AMARILLA_DOBLE,
    FLOR_AMARILLA_DOBLE_CHICA,

    FLOR_NARANJA,
    FLOR_NARANJA_CHICA,
    FLOR_NARANJA_DOBLE,
    FLOR_NARANJA_DOBLE_CHICA,


    PELOTA_BLANCA,
    PELOTA_BLANCA_CHICA,
    PELOTA_BLANCA_DOBLE,
    PELOTA_BLANCA_DOBLE_CHICA,

    PELOTA_ROJA,
    PELOTA_ROJA_CHICA,
    PELOTA_ROJA_DOBLE,
    PELOTA_ROJA_DOBLE_CHICA,

    PELOTA_AZUL,
    PELOTA_AZUL_CHICA,
    PELOTA_AZUL_DOBLE,
    PELOTA_AZUL_DOBLE_CHICA,

    PELOTA_AMARILLA,
    PELOTA_AMARILLA_CHICA,
    PELOTA_AMARILLA_DOBLE,
    PELOTA_AMARILLA_DOBLE_CHICA,

    PELOTA_NARANJA,
    PELOTA_NARANJA_CHICA,
    PELOTA_NARANJA_DOBLE,
    PELOTA_NARANJA_DOBLE_CHICA,


    PERRO_BLANCO,
    PERRO_BLANCO_CHICO,
    PERRO_BLANCO_DOBLE,
    PERRO_BLANCO_DOBLE_CHICO,

    PERRO_ROJO,
    PERRO_ROJO_CHICO,
    PERRO_ROJO_DOBLE,
    PERRO_ROJO_DOBLE_CHICO,

    PERRO_AZUL,
    PERRO_AZUL_CHICO,
    PERRO_AZUL_DOBLE,
    PERRO_AZUL_DOBLE_CHICO,

    PERRO_AMARILLO,
    PERRO_AMARILLO_CHICO,
    PERRO_AMARILLO_DOBLE,
    PERRO_AMARILLO_DOBLE_CHICO,

    PERRO_NARANJA,
    PERRO_NARANJA_CHICO,
    PERRO_NARANJA_DOBLE,
    PERRO_NARANJA_DOBLE_CHICO
}
